Add migration script that only relies on v2
woefe/ytcc pull request #51
Opened 2020-10-05 20:56 UTC by woefe

This migration script relies only on v2 being installed and available as Python import. It reads subscriptions and videos directly from the v1 SQL database and adds them to a v2 database. The duration column in v2 is always set to zero.

2020-10-05 21:07 UTC, woefe commented
@EmRowlands Can you try this migration script on your setup and also let me know if it works okay?

2020-10-06 14:50 UTC, EmRowlands requested changes
I think the only thing I would suggest is sending errors to `stderr`. Other than that, this looks good! I have tested it and it works for me, producing an identical database (except with different `videoid`s) to the one I created.

2020-10-06 14:50 UTC, EmRowlands commented on scripts/migrate.py
> +    print("Error:", message)
I suggest sending errors to `stderr`
```suggestion
    print("Error:", message, file=sys.stderr)
```

2020-10-06 19:33 UTC, merged

2020-10-06 19:33 UTC, woefe commented
@EmRowlands Thank you very much for your feedback and your help on this PR! ❤ And sorry that that I didn't merge your efforts from #50.

2020-10-06 19:38 UTC, EmRowlands commented
Hey, no need to apologise. I use ytcc pretty much every day and I'm happy to help in any way I can. Be it writing code, reviewing code, or just submitting bugs.